dist: xenial
sudo: required
language: python
cache: pip

git:
  submodules: true

python:
  - 3.8
services:
  - docker
install:
  - pip install tox-travis
after_failure:
  - echo "FUNNEL LOGS ----------"
  - cat ./tests/test_tmp/conformance_test_v1.0_*/funnel_log.txt
notifications:
  email: false

jobs:
  include:
    - stage: all
      script:
        - tox
    - script:
        - make funnel
        - make ftp-server
        - make funnel-server
        - make ftp-test
      env:
        - n=ftp
